//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapItPrices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetaInviteCodes
    {
        public string InviteCode { get; set; }
        public bool IsUsed { get; set; }
    }
}
