//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MapItPrices.Models
{
    public partial class BetaInviteCodes
    {
        #region Primitive Properties
    
        public virtual string InviteCode
        {
            get;
            set;
        }
    
        public virtual bool IsUsed
        {
            get;
            set;
        }
    
        public virtual string User_ID
        {
            get;
            set;
        }

        #endregion
    }
}
