//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapItPrices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.UPC = "null";
            this.StoreItems = new HashSet<StoreItem>();
            this.ShoppingLists = new HashSet<ShoppingList>();
            this.Categories = new HashSet<Category>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string UPC { get; set; }
        public string Size { get; set; }
        public int UserID { get; set; }
        public string Brand { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ICollection<StoreItem> StoreItems { internal get; set; }
        public virtual User User { internal get; set; }
        public virtual ICollection<ShoppingList> ShoppingLists { internal get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
