//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapItPrices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapItPricesEntities : DbContext
    {
        public MapItPricesEntities()
            : base("name=MapItPricesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Item> Items { get; set; }
        public DbSet<StoreItem> StoreItems { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<OpenID> OpenIDs { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Badge> Badges { get; set; }
        public DbSet<BetaInviteCodes> BetaInviteCodes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<ShoppingList> ShoppingLists { get; set; }
        public DbSet<BetaSignup> BetaSignups { get; set; }
        public DbSet<Category> Categories { get; set; }
    }
}
