//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MapItPrices.Models
{
    public partial class ShoppingList
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.ID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private int _userID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual System.DateTime Created
        {
            get;
            set;
        }
    
        public virtual System.DateTime LastUpdated
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual ICollection<Item> Items
        {
            get
            {
                if (_items == null)
                {
                    var newCollection = new FixupCollection<Item>();
                    newCollection.CollectionChanged += FixupItems;
                    _items = newCollection;
                }
                return _items;
            }
            set
            {
                if (!ReferenceEquals(_items, value))
                {
                    var previousValue = _items as FixupCollection<Item>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupItems;
                    }
                    _items = value;
                    var newValue = value as FixupCollection<Item>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupItems;
                    }
                }
            }
        }
        private ICollection<Item> _items;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.ShoppingLists.Contains(this))
            {
                previousValue.ShoppingLists.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.ShoppingLists.Contains(this))
                {
                    User.ShoppingLists.Add(this);
                }
                if (UserID != User.ID)
                {
                    UserID = User.ID;
                }
            }
        }
    
        private void FixupItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Item item in e.NewItems)
                {
                    if (!item.ShoppingLists.Contains(this))
                    {
                        item.ShoppingLists.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Item item in e.OldItems)
                {
                    if (item.ShoppingLists.Contains(this))
                    {
                        item.ShoppingLists.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
