//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MapItPrices.Models
{
    public partial class Store
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string State
        {
            get;
            set;
        }
    
        public virtual string Zip
        {
            get;
            set;
        }
    
        public virtual Nullable<double> Latitude
        {
            get;
            set;
        }
    
        public virtual Nullable<double> Longitude
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (User != null && User.ID != value)
                    {
                        User = null;
                    }
                    _userID = value;
                }
            }
        }
        private int _userID;
    
        public virtual System.DateTime Created
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        internal virtual ICollection<StoreItem> StoreItems
        {
            get
            {
                if (_storeItems == null)
                {
                    var newCollection = new FixupCollection<StoreItem>();
                    newCollection.CollectionChanged += FixupStoreItems;
                    _storeItems = newCollection;
                }
                return _storeItems;
            }
            set
            {
                if (!ReferenceEquals(_storeItems, value))
                {
                    var previousValue = _storeItems as FixupCollection<StoreItem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStoreItems;
                    }
                    _storeItems = value;
                    var newValue = value as FixupCollection<StoreItem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStoreItems;
                    }
                }
            }
        }
        private ICollection<StoreItem> _storeItems;
    
        public virtual User User
        {
            internal get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Stores.Contains(this))
            {
                previousValue.Stores.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Stores.Contains(this))
                {
                    User.Stores.Add(this);
                }
                if (UserID != User.ID)
                {
                    UserID = User.ID;
                }
            }
        }
    
        private void FixupStoreItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (StoreItem item in e.NewItems)
                {
                    item.Store = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (StoreItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.Store, this))
                    {
                        item.Store = null;
                    }
                }
            }
        }

        #endregion
    }
}
