//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapItPrices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.OpenIDs = new HashSet<OpenID>();
            this.StoreItems = new HashSet<StoreItem>();
            this.Items = new HashSet<Item>();
            this.Stores = new HashSet<Store>();
            this.Badges = new HashSet<Badge>();
            this.Roles = new HashSet<Role>();
            this.ShoppingLists = new HashSet<ShoppingList>();
        }
    
        public string Email { get; set; }
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string Password { get; set; }
        public string SessionToken { get; set; }
    
        public virtual ICollection<OpenID> OpenIDs { get; set; }
        public virtual ICollection<StoreItem> StoreItems { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
        public virtual ICollection<Badge> Badges { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<ShoppingList> ShoppingLists { get; set; }
    }
}
